### ISSUE TITLE
Support C# 7 tuple display

### ISSUE THREAD

**Issue by MrJul** [MrJul/ReSharper.EnhancedTooltip#103]

**Comment by silkfire** [comment]
@MrJul This doesn't seem to be working for me at the moment.

Without EnhancedTooltip, it's displayed correctly:

![image](https://user-images.githubusercontent.com/1554615/57254557-dfbedc00-7051-11e9-958f-c0fbffa752dc.png)

With ET _enabled_, it shows the old-style `Item1`, `Item2` instead (along with `System.ValueTuple<>`):

![image](https://user-images.githubusercontent.com/1554615/57254603-f9602380-7051-11e9-9c67-bea766e2e290.png)

**Comment by MrJul** [comment]
I can't seem to reproduce the problem:
![image](https://user-images.githubusercontent.com/1623034/57286557-c5b6e500-70b5-11e9-80d1-5234efbb5096.png)

Do you have more information such as the project type, targeted runtime and exact signature?

**Comment by silkfire** [comment]
Could it have to do with that ReSharper provides the wrong information?

![image](https://user-images.githubusercontent.com/1554615/57293777-f0a93500-70c5-11e9-8987-caf09e06d862.png)

See the tooltip to the right that is shown when browsing IntelliSense suggestions.

**Comment by silkfire** [comment]
1. When hovering over either of the value tuple components, I get the standard tooltip instead of ET.
![image](https://user-images.githubusercontent.com/1554615/57303651-10e4ee00-70de-11e9-82e2-dca9012dab88.png)
2. (unrelated) When hovering right inbetween `var` and `y`, I get the standard tooltip too:
![image](https://user-images.githubusercontent.com/1554615/57303823-7042fe00-70de-11e9-875f-a3be198593a4.png)
3. Hovering on one of the tuple components in an assignment statement shows `Item1 … Item2` instead (undesired behaviour):
![image](https://user-images.githubusercontent.com/1554615/57304008-c6b03c80-70de-11e9-96d4-c46b0d5c9972.png)

**Comment by silkfire** [comment]
@MrJul Is there any status on this?
