### ISSUE TITLE
Still broken without Resharper C++ & double tooltip when turned off

### ISSUE THREAD

**Issue by CADbloke** [MrJul/ReSharper.EnhancedTooltip#126]
as per https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/118#issuecomment-374385977 Installing R# C++ fixes the last remnants what VS 15.6 broke.

Also, displays an extra un-enhanced tooltip when "Enhance identifier tooltips" is unchecked. VS 15.6.3, R# 2017.3.3

![unenhancedtooltip](https://user-images.githubusercontent.com/147329/37687404-9f52aef4-2cef-11e8-8a2e-29dd93780d1d.png)

Is all good with R# C++ installed when "Enhance identifier tooltips" is checked. 🥇 
![enhancedtooltip-180321a](https://user-images.githubusercontent.com/147329/37687548-189d8bbc-2cf0-11e8-8194-29b8f0ecf9e4.png)

**Comment by MrJul** [comment]
Regarding the double tooltip, since you disabled "enhance identifier tooltips", please make sure that *Replace Visual Studio tooltip* is checked in ReSharper's Options → Environment → Editor → Editor Appearance. This is not related to Enhanced Tooltip directly.

Regarding ReSharper C++ , let's keep this issue to track it, thanks for the report!
