### ISSUE TITLE
ReSharper 2020.3 is not supported

### ISSUE THREAD

**Issue by NN---** [MrJul/ReSharper.EnhancedTooltip#161]

**Comment by NW7US** [comment]
Any movement on getting an updated version that would be supported in R# 2020.3?  I really LOVE the effectiveness that comes from having this extension usable in my daily workflow.  Here's hoping that it will become available very soon.

**Comment by Decimation** [comment]
Same here, I would love to see 2020.3 support.

**Comment by mvonballmo** [comment]
Just offering some encouragement on support for 2020.3. I've been a fan of this extension for years.

**Comment by GvmiHasan** [comment]
Hi @CADbloke, Can you help people having a good Christmas? 🤶😁

**Comment by CADbloke** [comment]
The Nuget update to the latest R# SDK failed for me. I'm giving up early and rolling back to a version of R# they haven't broken for the rest of us. Get 2020.2.5 at https://www.jetbrains.com/resharper/download/previous.html 

````
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for JetBrains.Platform.UIInteractive.Ide. Install/reference JetBrains.Platform.UIInteractive.Ide 203.0.20201223.80504 directly to project GammaJul.ReSharper.EnhancedTooltip to resolve this issue. 
 GammaJul.ReSharper.EnhancedTooltip -> JetBrains.ReSharper.SDK 2020.3.1 -> JetBrains.ReSharper.SDK.Internal 203.0.20201223.84329 -> JetBrains.Psi.Features.VisualStudio 203.0.20201223.81137 -> JetBrains.Psi.Features.UIInteractive.SolutionAnalysis 203.0.20201223.81137 -> JetBrains.Psi.Features.UIInteractive.Core 203.0.20201223.81137 -> JetBrains.Platform.UIInteractive.Ide (>= 203.0.20201223.80504 && < 203.1.0) 
 GammaJul.ReSharper.EnhancedTooltip -> JetBrains.Platform.VisualStudio 202.0.20200810.170838 -> JetBrains.Platform.UIInteractive.Ide (>= 202.0.20200810.170838 && < 202.1.0).	GammaJul.ReSharper.EnhancedTooltip	C:\Codez\Github\ReSharper.EnhancedTooltip\source\GammaJul.ReSharper.EnhancedTooltip\GammaJul.ReSharper.EnhancedTooltip.csproj	1	
````

**Comment by DimitarCC** [comment]
SDK is fine installs and with minor fixes of the code i was able to build a version supported in 2020.3

**Comment by NN---** [comment]
@CADbloke You have to update both SDK and VisualStudio packages: #162

**Comment by Mike-E-angelo** [comment]
Hi all... I am a little confused here, apologies.  I was able to install this extension for 2020.3.  However, tooltips no longer worked so had to uninstall.  Is that this issue here?  Reading over this issue makes it seem like the issue is not being available at all, when that doesn't seem to be the case.

**Comment by zeldafreak** [comment]
@Mike-E-angelo Though it's possible it's changed since I checked last week, after I updated to 2020.3 this extension was not installable unless I checked the **Include prerelease packages** checkbox in ReSharper's settings. But the version that gets installed is very old and, as you mentioned, doesn't work. I ended up rolling back to ReSharper 2020.2.5 [as suggested by @CADbloke](https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/161#issuecomment-751920249).

**Comment by Mike-E-angelo** [comment]
Thank you for taking the time to explain, @zeldafreak. 👍

**Comment by Mike-E-angelo** [comment]
Hey @matkoch care to work your magic here as well? 😁

**Comment by matkoch** [comment]
I can check on updating the plugin, but I can't update it on the marketplace, unfortunately. I contacted Julien before already, need to wait for that.

**Comment by MrJul** [comment]
Sorry for the long delay, Enhanced Tooltip v3.15 for ReSharper 2020.3.2 has been pushed to the JetBrains Gallery (pending approval).

**Comment by Mike-E-angelo** [comment]
Thank you, @MrJul!

**Comment by zeldafreak** [comment]
FOSS maintenance is thankless work, but here's a big **THANK YOU** anyway :)
