### ISSUE TITLE
The ET sometimes acts as if it's disabled

### ISSUE THREAD

**Issue by MrJul** [MrJul/ReSharper.EnhancedTooltip#27]
Reported on ReSharper 8.2.3 only.
Repro steps or possible exception needed.

**Comment by dsaf** [comment]
I have made an observation that when ET stops working tooltip "rolls back" to the Visual Studio's one not even ReSharper's one. Could it be a ReSharper bug?

**Comment by MrJul** [comment]
I'm not sure. Are identifier still highlighted by ReSharper? Nothing in VS activility log?

**Comment by dsaf** [comment]
Yes, identifiers are still highlighted. Did not see anything related in VS activity log.

**Comment by MrJul** [comment]
After two months of usage, I still haven't seen this bug once in ReSharper 9.0.
The problem is probably related to the VS integration package in 8.2. Do you have any new piece of information?

**Comment by dsaf** [comment]
All I can say is that it is definitely present in ReSharper 8.2.3 on my machine. No new information unfortunately. Maybe it is not worth spending time on. The only reason I am still using 8.2.3 is because 9.0 doesn't have enough features for our team lead to go through the pain of paying for it via company's accounting department.

**Comment by MrJul** [comment]
ReSharper v8.2 won't be supported anymore in Enhanced Tooltip v2.4 so I'm closing this issue.
