### ISSUE TITLE
ParameterInfo colorization not working?

### ISSUE THREAD

**Issue by rog1039** [MrJul/ReSharper.EnhancedTooltip#43]
Not sure what I've done to my parameter info but I assume this isn't how it is supposed to look:

![2015-04-23 19_20_46 microsoft visual studio](https://cloud.githubusercontent.com/assets/5702706/7309594/6c5018bc-e9ee-11e4-9639-808803254c26.png)

![2015-04-23 19_30_29 microsoft visual studio](https://cloud.githubusercontent.com/assets/5702706/7309675/4c5a63fe-e9ef-11e4-875d-ddb304386a3f.png)

My settings look like this:
![2015-04-23 19_35_34-options](https://cloud.githubusercontent.com/assets/5702706/7309716/f980aa02-e9ef-11e4-8f90-c6a94e2675e1.png)
![2015-04-23 19_35_19-options](https://cloud.githubusercontent.com/assets/5702706/7309718/f9847416-e9ef-11e4-8c67-b6cd11d37a15.png)
![2015-04-23 19_35_00-options](https://cloud.githubusercontent.com/assets/5702706/7309717/f9835202-e9ef-11e4-8616-e959aaf25ff0.png)

and my VS and Resharper are both up-to-date I believe:
![2015-04-23 19_38_11 microsoft visual studio](https://cloud.githubusercontent.com/assets/5702706/7309742/609b19f2-e9f0-11e4-9a2e-dabde0559198.png)
![2015-04-23 19_37_43-about microsoft visual studio](https://cloud.githubusercontent.com/assets/5702706/7309743/609b94d6-e9f0-11e4-876f-d7cf5b69967f.png)

Any idea what might have happened?  Or do I have some setting not set correctly?

Thanks!

**Comment by MrJul** [comment]
I've seen this too, randomly. On some VS hives it always works, on others it doesn't at all.

After debugging, this seems to be a problem with the way ReSharper sorts components: the order is non deterministic. Sometimes the built-in one from ReSharper wins, sometimes Enhanced Tooltip wins.

For some reason I've only noticed this issue with ReSharper 9.1. Either the component model have changed in some ways between 9.0 and 9.1, or I was lucky before.

@citizenmatt Pinging you :) `EditorParameterInfoHandler.CreateContext` enumerates all `IParameterInfoContextFactory` and uses the last matching one. The problem stems from ET's `EnhancedParameterInfoContextFactory` that doesn't override `CSParameterInfoContextFactory`. But it can't since it's internal (IMO it shouldn't, most other implementations are public). I haven't found any way to explicitly specify the order, is there any?

**Comment by citizenmatt** [comment]
Ugh. Internal. We don't have many internal classes, they're such a pain. No, I don't see any other way of specifying order. And because it's internal, you can't even use `IHideImplementation<T>`. Sorry...

**Comment by MrJul** [comment]
Thank you Matt, I was kinda expecting this answer :(
Can it be made public for the next wave?

**Comment by citizenmatt** [comment]
Should think so. Add an issue, and explain what's going on, we've changed tons of stuff from internal before.

**Comment by MrJul** [comment]
Reported [RSRP-438206](https://youtrack.jetbrains.com/issue/RSRP-438206).

@rog1039 Sorry, I can't do much here until the next ReSharper version :(
You can try to reinstall and see if you have more luck (that's not really practical, I know).

**Comment by rog1039** [comment]
@MrJul No problem at all, thanks for looking into the problem, I appreciate it!  Hopefully the next release of ReSharper makes a fix possible.

This extension is still awesome even without ParameterInfo highlighting.

**Comment by DevHim** [comment]
@MrJul since RSRP-438206 is fixed now, I hope this would be fixed in next release, 9.2?
Great extn, btw!!

**Comment by MrJul** [comment]
Fixed in 2.5.1, for ReSharper 9.2 only.
