### ISSUE TITLE
Missing parameter info for type parameters

### ISSUE THREAD

**Issue by citizenmatt** [MrJul/ReSharper.EnhancedTooltip#60]
Given a piece of code like:

``` csharp
public class Foo : Bah<Quux>
{
}
```

If I invoke parameter info with the text caret in the type parameter part of the base class declaration (where the `Quux` is), I get a boring old plain black and white parameter info, instead of a lovely, colourful _enhanced_ tooltip.

**Comment by MrJul** [comment]
@citizenmatt I've implemented this!

However, I had to use some reflection because `TypeArgumentCandidate.myTypeElement` and `TypeArgumentCandidate.myLanguage` aren't exposed (`myLanguage` can be worked around, but not `myTypeElement`). Do you think some public properties can be added to the next ReSharper version for these two fields?

**Comment by derigel23** [comment]
@MrJul Sure, expect in 2017.1 EAP4

**Comment by MrJul** [comment]
@derigel23 Awesome! Thank you :)

**Comment by citizenmatt** [comment]
Hooray! Thanks both :)
