### ISSUE TITLE
Tooltip position is significantly offset in some cases

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#70]
Not sure where is the positioning code located (IDE, ReSharper, ET), so it might not be fixable.

Steps to reproduce (if reproducible):

1) navigate to Entity Framework's ```System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<> ``` class sources;
2) go to lines 60-62;
3) hover over any of code elements and observe the offset tooltip:

![image](https://cloud.githubusercontent.com/assets/3845650/10428915/9393f51c-70ec-11e5-97aa-a76634e608b1.png)

It's the first time I am seeing this, not really a problem for me personally. Thanks.

**Comment by MrJul** [comment]
I can reproduce this: my tooltip isn't as shifted as yours, but there's definitely something wrong.

After investigation, the option "display the role of arguments" seems to be the culprit. Since the role spans 5 lines here, the tooltip is shown outside, and it doesn't change as long as the role doesn't.

IMO, the role shouldn't affect the tracking span of the tooltip.

**Comment by dsaf** [comment]
Yes, I can see it in more places now. It also stops the tooltip from being retriggered on a different element of the same line / some region.
