### ISSUE TITLE
Support for R# 2016.2

### ISSUE THREAD

**Issue by DevHim** [MrJul/ReSharper.EnhancedTooltip#91]
An early release is deeply appreciated as this is one of the first add-ins I install after every R# release.
Thanks for the good work!! :)

**Comment by CodingGorilla** [comment]
I've forked and fixed all the errors caused by the upgrade to the 2016.2 platform [here](https://github.com/CodingGorilla/ReSharper.EnhancedTooltip/tree/feature/resharper-2016.2).  I have it running locally in my own VS 2015 instance, but there is one issue that I am checking on with the R# plugin group before I make these changes publicly available.

If you want to compile it yourself and install it locally it's pretty simple to do, otherwise I will submit a pull request to @MrJul when I get some confirmation of my issue.

**Comment by MrJul** [comment]
I was planning on working on it tonight (CET time). There aren't many changes so it should be quick. @CodingGorilla If you're done by that time, I'll gladly accept a PR! What's your issue?

**Comment by CodingGorilla** [comment]
@MrJul Yea, it's done and running locally.  The issue is [here](https://github.com/CodingGorilla/ReSharper.EnhancedTooltip/commit/28fea2a32e7622402e0371077de2b784bf13fff0) ; the `Context` property was removed from `IDocumentMarkup` interface, so in order to get the `Context.Locks` I had to cast it to `DocumentMarkupBase`.  This seems safe because all the implementations I could find inherit from this class.  But since it's an unsafe cast (and I'm not sure how else to get the equivalent property) I wanted to double check it.

**Comment by citizenmatt** [comment]
Just to jump in - I don't think there's really anything wrong with this. Perhaps downcast to `IDocumentMarkupImpl` instead. I haven't checked with the team why it was moved. I guess separation of concerns - `IDocumentMarkup` is about adding/getting highlighters and `IDocumentMarkupImpl` is the other side of the interface - notifications on changes to highlighters or the document.

**Comment by MrJul** [comment]
I was using `Context.Locks` because it was conveniently available on the document. I think the line can safely be replaced by a call to `Shell.Instance.Resolve<IShellLocks>()`.

**Comment by CodingGorilla** [comment]
@MrJul  There is no `Shell.Instance.Resolve<>()` (anymore?), Same as `Shell.Instance.GetComponent<>()`?

I'll admit, I'm a R# plugin newbie and I have very little idea what I'm doing! :grinning:

**Comment by citizenmatt** [comment]
`Shell.Instance.GetComponent<T>()`

**Comment by CodingGorilla** [comment]
OK, done, PR incoming.

**Comment by MrJul** [comment]
Thanks to @CodingGorilla, Enhanced Tooltip is now available for ReSharper 2016.2!

**Comment by rob8861** [comment]
Hello, 
Just to let you guys know, the extension is still not available under the extension manager for 2016.2
can you please advise.
Thank you,

**Comment by rob8861** [comment]
okay I figured out why I couldn't see it. the solution, in case someone else is running into the same issue, the extensions for 2016.2 are visible under wave 6 which was not updated automatically by the installer. I will file a bug report with Resharper.
